const products = [
  {
    _id: "67rdca3eeb7f6f324geed471815",
    name: "Foxxx Kitsune Mini Black Vintage RCA",
    price: 6000,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/machines/foxx-kitsune.png",
    absent: false,
    hit: true,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgee4234d471816",
    name: "Foxxx Viper Fox Golden Vintage Lot #1 RCA",
    price: 8730,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/machines/foxx-viper.png",
    absent: false,
    hit: true,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: true
  },
  {
    _id: "67rdca3eeb437f655fgeed471818",
    name: "Forever Cartridge Grip Ergo 30 mm Огненно-Рыжий",
    price: 2037,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/cartridge/cartridge-grip.png",
    absent: false,
    hit: false,
    novelty: true,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fg46662eed471819",
    name: "Verge Direct 2.1 Pink gip EGO 4 mm liners",
    price: 2037,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/machines/verge-direct2.1.png",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed42371820",
    name: "Deuce Machines Direct Drive #7 RCA Samurai",
    price: 8000,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/machines/deuce-machines.png",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6f3223geed471821",
    name: "Cyborg Machines Alter Rotary Axis Cross Sexy Nymph",
    price: 11000,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/machines/cyborg-machine.png",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771822",
    name: "Verge Direct 2.1 Gunmetal",
    price: 10900,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/machines/verge-direct.png",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771823",
    name: "Verge Direct Black",
    price: 14260,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/machines/verge-direct-black.png",
    absent: false,
    hit: false,
    novelty: true,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771824",
    name: "V-machine Shader",
    price: 7800,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/machines/V-machine-Shader.jpg",
    absent: false,
    hit: true,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771825",
    name: "Tattoomechanics-W-Liner",
    price: 12300,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/machines/Tattoomechanics-W-Liner.jpg",
    absent: false,
    hit: true,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771826",
    name: "MT Vader Pen",
    price: 6520,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/machines/MT-Vader-Pen.png",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771827",
    name: "Skinductor Vertigo",
    price: 9700,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/machines/skinductor-vertigo.png",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771828",
    name: "Sign Red",
    price: 11253,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/machines/sign-red.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771829",
    name: "Rogers Power Liner",
    price: 17850,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/machines/Rogers-Power-Liner.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771830",
    name: "Hummingbird Gold",
    price: 13580,
    favorite: false,
    sales: 0.35,
    url: "../../assets/productsCards/machines/Hummingbird-Gold.jpg",
    absent: true,
    hit: false,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771830",
    name: "Heavy ong Stroke",
    price: 10000,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/machines/Heavy-ong-Stroke.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771831",
    name: "Foxx-minigold",
    price: 11300,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/machines/foxx-minigold.png",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771832",
    name: "Fly RCA Gold",
    price: 4750,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/machines/Fly-RCA-Gold.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771833",
    name: "Dm mechanics Direct",
    price: 22540,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/machines/Dm-mechanics-Direct.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771834",
    name: "Deuce Machines Slider",
    price: 18900,
    favorite: false,
    sales: 0.2,
    url: "../../assets/productsCards/machines/Deuce-Machines-Slider.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771835",
    name: "CNC X WE Wireless.png",
    price: 15660,
    favorite: false,
    sales: 0.2,
    url: "../../assets/productsCards/machines/CNC-X-WE-Wireless.png",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771836",
    name: "Boss Rotary Blue",
    price: 16220,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/machines/Boss-Rotary-Blue.jpg",
    absent: false,
    hit: false,
    novelty: true,
    promotion: false,
    category: "machines",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771837",
    name: "Aluminium Grip 25mm C",
    price: 4300,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/cartridge/AluminiumGrip25mmC.jpg",
    absent: false,
    hit: false,
    novelty: true,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771838",
    name: "Black Ally Laser Etch Grip",
    price: 2800,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/cartridge/BlackAllyLaserEtchGrip.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771839",
    name: "Coil Grip 25мм",
    price: 2750,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/cartridge/CoilGrip25мм.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771840",
    name: "EXODUS",
    price: 3200,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/cartridge/ExcaliburGripMagnum19.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771841",
    name: "Excalibur Grip Magnum 19",
    price: 5700,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/cartridge/EXODUSHANDPOKETOOLSSKRIKCO2.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771842",
    name: "EXODUS HANDPOKE TOOLS SON OF MAN CO2",
    price: 6200,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/cartridge/EXODUS HANDPOKE TOOLS SON OF MAN CO2.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771843",
    name: "EZ Steel Cartridge Grip 25mm",
    price: 3500,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/cartridge/EZ Steel Cartridge Grip 25mm A.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771844",
    name: "EZ Twist Rings Adjustable Cartridge Grip",
    price: 3600,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/cartridge/EZ Twist Rings Adjustable Cartridge Grip 32 mm Camo Red.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771845",
    name: "Fish Bone 22 мм.jpg",
    price: 1700,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/cartridge/Fish Bone 22 мм.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771846",
    name: "Forever Cartridge Grip",
    price: 2250,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/cartridge/Forever Cartridge Grip.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771847",
    name: "Memory Foam Cover",
    price: 3450,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/cartridge/Memory Foam Cover.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771848",
    name: "Mustang Grip 20 мм",
    price: 4110,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/cartridge/Mustang Grip 20 мм.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771849",
    name: "Rattler 22 mm.",
    price: 3600,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/cartridge/Rattler 22 mm.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771850",
    name: "T-tech Cheyenne Hawk Grip Orange",
    price: 4270,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/cartridge/T-tech Cheyenne Hawk Grip Orange.jpg",
    absent: false,
    hit: false,
    novelty: true,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771851",
    name: "Verge Disposable Grip Flat 5F",
    price: 2960,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/cartridge/Verge Disposable Grip Flat 5F (30 mm).jpg",
    absent: false,
    hit: false,
    novelty: true,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771852",
    name: "Verge Disposable Grip Round 3R",
    price: 5230,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/cartridge/Verge Disposable Grip Round 3R (19 mm).jpg",
    absent: false,
    hit: false,
    novelty: true,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771853",
    name: "Verge Disposable Grip Crotus 3R (30 mm)",
    price: 4620,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/cartridge/Verge Disposable Grip Round 3R (30 mm).jpg",
    absent: false,
    hit: false,
    novelty: true,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771854",
    name: "Verge Grip 30 мм",
    price: 2580,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/cartridge/Verge Grip 30 мм.jpg",
    absent: false,
    hit: false,
    novelty: true,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771855",
    name: "Vertigo S Grip",
    price: 3460,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/cartridge/Vertigo S Grip.jpg",
    absent: false,
    hit: false,
    novelty: true,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771856",
    name: "Wasp 25 mm",
    price: 3330,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/cartridge/Wasp 25 mm.jpg",
    absent: false,
    hit: false,
    novelty: true,
    promotion: false,
    category: "cartridge",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771857",
    name: "Tattoo Up Aquamarine 250 мл.",
    price: 1700,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/consumables/attoo Up Aquamarine 250 мл.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771858",
    name: "benovy xl 15",
    price: 90,
    favorite: false,
    sales: 0.2,
    url: "../../assets/productsCards/consumables/benovy xl 15.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771859",
    name: "Consumabel-Box",
    price: 2300,
    favorite: false,
    sales: 0.3,
    url: "../../assets/productsCards/consumables/consumabelbox.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771860",
    name: "Defender 50x1140.",
    price: 800,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/consumables/defender 50x1140.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771861",
    name: "Druid Trefoil Tattoo Butter",
    price: 750,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/consumables/Druid Trefoil Tattoo Butter",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771862",
    name: "Fingercups",
    price: 100,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/consumables/fingercups.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771863",
    name: "Holy Dew",
    price: 500,
    favorite: false,
    sales: 0.2,
    url: "../../assets/productsCards/consumables/Holy Dew.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771864",
    name: "Ilk Way XXL",
    price: 2300,
    favorite: false,
    sales: 0.25,
    url: "../../assets/productsCards/consumables/ilk Way XXL.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771865",
    name: "pl-80",
    price: 1100,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/consumables/pl-80.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771866",
    name: "Premium ink cup 11мм",
    price: 1300,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/consumables/Premium ink cup 11мм.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771867",
    name: "Proskills Full Set",
    price: 1500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/consumables/Proskills Full Set.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771868",
    name: "SaintNitizer 300 мл",
    price: 300,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/consumables/SaintNitizer 300 мл.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771869",
    name: "Sivak  black",
    price: 650,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/consumables/Sivak  black.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771870",
    name: "Tattoo Revive Protective Tattoo Film",
    price: 1200,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/consumables/Tattoo Revive Protective Tattoo Film 15.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771871",
    name: "Tattoo UP 50 мл",
    price: 450,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/consumables/Tattoo UP 50 мл.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771872",
    name: "Tattoo UP Organic Basic Oil",
    price: 900,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/consumables/Tattoo UP Organic Basic Oil 100 мл.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771873",
    name: "Unista 13 мм",
    price: 750,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/consumables/Unista 13 мм.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771874",
    name: "Verge Disposable Machine Bags",
    price: 1400,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/consumables/Verge Disposable Machine Bags.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771875",
    name: "Yellow laps",
    price: 500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/consumables/yellow laps.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771876",
    name: "Вазелин Foxxx Vaseline French Vanilla",
    price: 850,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/consumables/Вазелин Foxxx Vaseline French Vanilla.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "consumables",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771877",
    name: "5 Fine Liner - 0,30 mm - Long",
    price: 1890,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/needles/5 Fine Liner - 0,30 mm - Long - Extra Tight.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771878",
    name: "11R (HummingBird Grip 25mm)",
    price: 1450,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/needles/11R (HummingBird Grip 25mm).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771879",
    name: "35FT (Magnum Grmip 30mm)",
    price: 2456,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/needles/35FT (Magnum Grmip 30mm).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771880",
    name: "big swap-Round Shader-20",
    price: 1890,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/needles/big swap-Round Shader-20.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771881",
    name: "big-swap-14-Round Shader",
    price: 1890,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/needles/big-swap-14-Round Shader.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771882",
    name: "Round Liner -145-dragon-howk",
    price: 2500,
    favorite: false,
    sales: 0.2,
    url: "../../assets/productsCards/needles/Round Liner -145-dragon-howk.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771883",
    name: "Round Liner fly dragon",
    price: 2700,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/needles/Round Liner -145-fly dragon.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771884",
    name: "Round Liner Skydragon",
    price: 1450,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/needles/Round Liner -145-Skydragon.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771885",
    name: "Round Liner 5",
    price: 2100,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/needles/Round Liner 5.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771886",
    name: "Round Magnum  heavy style",
    price: 2890,
    favorite: false,
    sales: 0.25,
    url: "../../assets/productsCards/needles/Round Magnum  heavy style.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771887",
    name: "Round Magnum 5",
    price: 1320,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/needles/Round Magnum 5.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771888",
    name: "Round Magnum 100",
    price: 1650,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/needles/Round Magnum 100.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771889",
    name: "Verge Flat Shader 5",
    price: 2400,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/needles/Verge Flat Shader 5.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771890",
    name: "Verge Round Magnum 7",
    price: 3560,
    favorite: false,
    sales: 0.35,
    url: "../../assets/productsCards/needles/Verge Round Magnum 7.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771891",
    name: "VLAD HAIR LINER 11",
    price: 3500,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/needles/VLADHAIRLINER11.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771892",
    name: "Vlad Soft Magnum 17",
    price: 1200,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/needles/Vlad Soft Magnum 17.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771893",
    name: "VLAD TRUE LINER 14",
    price: 2640,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/needles/VLAD TRUE LINER 14.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771894",
    name: "WHITE BONE - 11RL.LT",
    price: 4700,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/needles/WHITE BONE ( БЕЛАЯ КОСТЬ ) - 11RL.LT.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771895",
    name: "WHITE BONE Rock - 18RL",
    price: 4250,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/needles/WHITE BONE ( БЕЛАЯ КОСТЬ ) - 18RL.LT.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771896",
    name: "Steel tips Round 9R",
    price: 2680,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/needles/Steel tips Round 9R.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "needles",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771897",
    name: " Кожа для тренировки A5 P-028",
    price: 1450,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/A5 P-028.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771898",
    name: " Кожа для тренировки A5 P-029.jpg",
    price: 1750,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/A5 P-029.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771899",
    name: " AVA Skull Tattoo Bottle Black",
    price: 740,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/AVA Skull Tattoo Bottle Black.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771900",
    name: " AVA SS PEN HOLDER",
    price: 2300,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/AVA SS PEN HOLDER.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771901",
    name: "BA-020 black",
    price: 1700,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/BA-020 black.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771902",
    name: "BK-220",
    price: 960,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/BK-220.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771903",
    name: "Гель проявочный",
    price: 2450,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/blusskygel.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771904",
    name: "Контейнер для утилизации",
    price: 1500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/container1500.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: true,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771905",
    name: "D-12",
    price: 6320,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/D-12.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: true,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771906",
    name: "Защита для татту-машинки",
    price: 2300,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/defender tattoo machines.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771907",
    name: " EZ Tattoo Travel Case 2",
    price: 3620,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/EZ Tattoo Travel Case 2.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771908",
    name: " Инструментарий для татту",
    price: 2550,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/kittotattoo.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771909",
    name: "Подставка L-8",
    price: 1500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/L-8.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771910",
    name: "Подставка L-15",
    price: 1450,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/L-15.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771911",
    name: "Поднос ML-18.jpg",
    price: 1200,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/ML-18.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771912",
    name: "Подставка MN-125",
    price: 1630,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/accessories/MN-125.png",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771897913",
    name: "Кольца O-Rings",
    price: 500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/O-Rings.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771914",
    name: "Подставка PS004",
    price: 1862,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/PS004.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771915",
    name: "Кейс PU-230",
    price: 3800,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/PU-230.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771916",
    name: "Кейс RO-310",
    price: 7420,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/RO-310.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: true,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771917",
    name: "Spirit Classic Thermal Transfer Paper",
    price: 1000,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/Spirit Classic Thermal Transfer Paper.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771918",
    name: "TA055 blue (300 мл)",
    price: 650,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/TA055 blue (300 мл).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771919",
    name: "Tondaus - TM (стерильный)",
    price: 950,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/Tondaus - TM (стерильный).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771920",
    name: "TONDAUS WHITE - 1 MM",
    price: 700,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/TONDAUS WHITE - 1 MM.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771921",
    name: "Drawing pencil",
    price: 1000,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/accessories/transfer-line.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "accessories",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771922",
    name: "Tattoo Kit - PROTON ME-45",
    price: 17360,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/attoo Kit - PROTON ME-45.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771923",
    name: "Tattoo Kit-MAST-5000",
    price: 15230,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/attoo Kit-MAST-5000.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771924",
    name: "Black Pearl Kit",
    price: 12500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Black Pearl Kit.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771925",
    name: "Fly Kit",
    price: 14230,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Fly Kit.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771926",
    name: "Pen Rotary Kit",
    price: 13200,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Pen Rotary Kit.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771927",
    name: "Pirate Kit",
    price: 14250,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Pirate Kit.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771928",
    name: "Recruit Rotary Kit",
    price: 11230,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Recruit Rotary Kit.jpg",
    absent: false,
    hit: false,
    novelty: true,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771929",
    name: "Tattoo Kit - BRONC V1",
    price: 15600,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Tattoo Kit - BRONC V1.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771930",
    name: "Tattoo Kit - Metis",
    price: 12780,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Tattoo Kit - Metis.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771931",
    name: "Tattoo Kit - MOSKIT STEEL",
    price: 19520,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Tattoo Kit - MOSKIT STEEL.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771932",
    name: "Tattoo Kit - TeVo CD1 yellow",
    price: 17520,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Tattoo Kit - TeVo CD1 yellow.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: true,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771933",
    name: "Tattoo Kit - TeVo DG2 black",
    price: 16540,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Tattoo Kit - TeVo DG2 black.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771934",
    name: "Tattoo Kit-9R",
    price: 14300,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Tattoo Kit-9R.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771935",
    name: "Tattoo Kit-10",
    price: 17860,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Tattoo Kit-10.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771936",
    name: "Tattoo Kit-Fox M",
    price: 14890,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/kits/Tattoo Kit-Fox M.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771937",
    name: "Tattoo KIT-UNICORN",
    price: 16700,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Tattoo KIT-UNICORN.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771938",
    name: "Tattoo Profi-5U",
    price: 23400,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Tattoo Profi-5U.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771939",
    name: "Tattoo Profi-7U",
    price: 25600,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Tattoo Profi-7U.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771940",
    name: "Drawing pencTattoo Profi-11",
    price: 23650,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/kits/Tattoo Profi-11.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771941",
    name: "Tattoo Profi-14",
    price: 18750,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Tattoo Profi-14.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771942",
    name: "Verge Combo Kit",
    price: 15400,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Verge Combo Kit.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771943",
    name: "Verge Rotary Kit",
    price: 19200,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/kits/Verge Rotary Kit.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "kits",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771944",
    name: "Allegory BLAK Lining and Shading",
    price: 750,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Allegory BLAK Lining and Shading.png",
    absent: false,
    hit: false,
    novelty: false,
    promotion: true,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771945",
    name: "Allegory White",
    price: 700,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Allegory White.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771946",
    name: "Black panter - Enigma (15 мл)",
    price: 700,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Black panter - Enigma (15 мл).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771947",
    name: "BLUE MAGIC INTENSIVE BLUE",
    price: 450,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/BLUE MAGIC INTENSIVE BLUE.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771948",
    name: "Color Enhancer-Blue",
    price: 500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Color Enhancer.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771949",
    name: "DragonHawk RED",
    price: 800,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/DragonHawk RED.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771950",
    name: "DUSTY ROSE ETERNAL",
    price: 850,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/DUSTY ROSE ETERNAL.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771951",
    name: "Dynamic Colors Triple Black",
    price: 900,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Dynamic Colors Triple Black.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771952",
    name: "Dynamic Colors White",
    price: 1000,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Dynamic Colors White.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771953",
    name: "Formula 23 Light Grey Wash",
    price: 740,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Formula 23 Light Grey Wash.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771954",
    name: "High White - trinity",
    price: 1200,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/High White - trinity.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771955",
    name: "HORITOMO FUDO BLUE BLACK - Solid Ink",
    price: 2300,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/HORITOMO FUDO BLUE BLACK - Solid Ink.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771956",
    name: "Intenze - Dragon Color Tattoo Ink Set",
    price: 9650,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Intenze - Dragon Color Tattoo Ink Set.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771957",
    name: "Lining & Shading Black",
    price: 820,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Lining & Shading Black.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771958",
    name: "Lining Black - Separator",
    price: 950,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Lining Black -separator.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771959",
    name: "Mast colors Set 7 - Dragon Hawk",
    price: 6520,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Mast colors Set 7 - Dragon Hawk.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771960",
    name: "MINT GREEN ETERNAL",
    price: 600,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/MINT GREEN ETERNAL.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771961",
    name: "Oriental Black - trinity",
    price: 1100,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Oriental Black - trinity.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771962",
    name: "RED MAGIC INTENSIVE RED",
    price: 1432,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/RED MAGIC INTENSIVE RED.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771963",
    name: "SOLID GOLD ETERNAL (30 МЛ)",
    price: 1250,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/SOLID GOLD ETERNAL (30 МЛ).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771964",
    name: "SULUAPE Black - Intenze",
    price: 890,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/SULUAPE Black - Intenze.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771965",
    name: "Sumi Black Intenze - Noir",
    price: 1500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Sumi Black Intenze.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771966",
    name: "Super Black - Nocturnal Tattoo",
    price: 570,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Super Black - Nocturnal Tattoo.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771967",
    name: "The Mixer - Separator",
    price: 770,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/The Mixer - Separator.png",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771968",
    name: "TIM HENDRICKS BLACK - Solid Ink",
    price: 1150,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/TIM HENDRICKS BLACK - Solid Ink.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771969",
    name: "Triple Black - Trinity",
    price: 950,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Triple Black -trinity.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771970",
    name: "Turbo Black - Radiant",
    price: 2700,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Turbo Black - Radiant.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771971",
    name: "Ultimate White -Arena",
    price: 1420,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Ultimate White -Arena.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771972",
    name: "Victor Portugal Ink V2",
    price: 970,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/paints/Victor Portugal Ink V2.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "paints",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771973",
    name: "Провод - D380 Black",
    price: 1200,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/D380 Black.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771974",
    name: "Провод - D380 Orange",
    price: 1200,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/D380 Orange.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771975",
    name: "Провод - D380 Red",
    price: 1200,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/D380 Red.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771976",
    name: "Педаль - Dragon FT-41 red",
    price: 2800,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/Dragon FT-41 red.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567719777",
    name: "Провод - Dragon High Quality RCA Cord black",
    price: 1500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/Dragon High Quality RCA Cord black.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567719778",
    name: "Педаль - Dragon KA-50",
    price: 2750,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/Dragon KA-50.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771979",
    name: "Педаль - DT-010",
    price: 2300,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/DT-010.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771980",
    name: "Педаль - LT-740",
    price: 4800,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/LT-740.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: true,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771981",
    name: "Провод - MAX S-350 red",
    price: 1400,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/MAX S-350 red.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771982",
    name: "Провод - MAX S-400 blue",
    price: 1720,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/MAX S-400 blue.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771983",
    name: "Педаль - MT-300D",
    price: 3200,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/MT-300D.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771984",
    name: "Провод - CLIP-CORD BW-300",
    price: 1700,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/PREMIUM QUALITY CLIP-CORD BW-300.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771985",
    name: "Провод - RCA-CORD Arena WY-048 red",
    price: 1630,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/PREMIUM RCA-CORD Arena WY-048 red.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771986",
    name: "Педаль - R-10G.",
    price: 2200,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/R-10G.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771987",
    name: "Провод - RCA RT035 black",
    price: 1540,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/RCA RT035 black.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771988",
    name: "Провод - RCA SM-90BK.jpg",
    price: 1650,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/pedals/RCA SM-90BK.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771989",
    name: "Провод - RCA Z-015 black.jpg",
    price: 1100,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/RCA Z-015 black.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771990",
    name: "Провод - RCA-корд EZ Master Flat blue",
    price: 1320,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/RCA-корд EZ Master Flat blue.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771991",
    name: "Педаль - Skull DS-700",
    price: 3200,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/Skull DS-700.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771992",
    name: "Педаль - Skull DS-750",
    price: 3500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/Skull DS-750.jpg",
    absent: false,
    hit: false,
    novelty: true,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771993",
    name: "Педаль - Skull DS-800",
    price: 3700,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/Skull DS-800.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771994",
    name: "Педаль - Skull LT-600",
    price: 4210,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/Skull LT-600.jpg",
    absent: false,
    hit: true,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771995",
    name: "Педаль - Skull W-003 red",
    price: 3250,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/Skull W-003 red.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771996",
    name: "Педаль - Spider D20",
    price: 3650,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/Spider D20.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656771996",
    name: "Педаль - Spider D20",
    price: 3650,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/Spider D20.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771997",
    name: "Провод - Tattoo Artists straight RCA",
    price: 1700,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/Tattoo Artists straight RCA.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771998",
    name: "Педаль - TFS-03M",
    price: 2800,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/TFS-03M.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656771999",
    name: "Педаль - TFS05",
    price: 3100,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/TFS05.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed455656772000",
    name: "Педаль - Tral P40 gold",
    price: 4500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/Tral P40 gold.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },

  {
    _id: "67rdca3eeb7f6fgeed4556567722001",
    name: "Педаль - TRIGO B-04 black",
    price: 3470,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/TRIGO B-04 black.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722002",
    name: "Провод - TeVo RCA - Yellow",
    price: 3470,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/pedals/Клип-корд TeVo RCA - yellow.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "pedals",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722003",
    name: "Блок - BRONC Hummingbird - V2",
    price: 8300,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/BRONC Hummingbird - V2.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722004",
    name: "Блок - BRONC Hummingbird - V3",
    price: 8000,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/BRONC Hummingbird - V3.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722005",
    name: "Блок - Dragon P-45 black",
    price: 7500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/Dragon P-45 black.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722006",
    name: "Блок - Dragon P-50",
    price: 7200,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/Dragon P-50.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722007",
    name: "Блок - Dragon P-60",
    price: 8300,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/Dragon P-60.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722008",
    name: "Блок - Dragon P-400",
    price: 6400,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/Dragon P-400.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722009",
    name: "Блок - Dragon P077 Black",
    price: 7400,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/Dragon P077 Black.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722010",
    name: "Блок - Dragon WX-3 black (DC)",
    price: 11200,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/Dragon WX-3 black (DC).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722011",
    name: "Блок - eVo G1 Black",
    price: 5250,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/eVo G1 Black.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722012",
    name: "Блок - Foxxx BUG Black-red",
    price: 6750,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/Foxxx BUG Black-red.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722013",
    name: "Блок - Foxxx BUG Yellow Stars",
    price: 7800,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/Foxxx BUG Yellow Stars.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722014",
    name: "Блок - Foxxx Detonator 3.1 Custom Pin Up",
    price: 12300,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/Foxxx Detonator 3.1 Custom Pin Up.jpg",
    absent: false,
    hit: false,
    novelty: true,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722015",
    name: "Блок - Foxxx Double Pulse V1 red",
    price: 7700,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/Foxxx Double Pulse V1 red.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722016",
    name: "Блок - Foxxx Drive v1 Orange",
    price: 7250,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/Foxxx Drive v1 Orange.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722017",
    name: "Блок - Foxxx Insecticons Box V2 Black-Red",
    price: 5500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/Foxxx Insecticons Box V2 Black-Red.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722018",
    name: "Блок - Foxxx Mandala BOX Lot 1",
    price: 10200,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/Foxxx Mandala BOX Lot 1.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722019",
    name: "Блок - Foxxx Spark Black",
    price: 9500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/Foxxx Spark Black.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722020",
    name: "Блок - LS-APT-5",
    price: 4400,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/LS-APT-5.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722021",
    name: "Блок - PS-024",
    price: 8300,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/PS-024.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722022",
    name: "Блок - Rainbow L300 black",
    price: 8900,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/Rainbow L300 black.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: true,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722023",
    name: "Блок - TeVo Astral",
    price: 7400,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/powers/TeVo Astral.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722024",
    name: "Блок - TeVo G2 Yellow",
    price: 6520,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/TeVo G2 Yellow.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722025",
    name: "Блок - TM-40",
    price: 7000,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/TM-40.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722026",
    name: "Блок - TPN-020 mini-black",
    price: 8100,
    favorite: false,
    sales: 0.1,
    url: "../../assets/productsCards/powers/TPN-020 mini, black.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722027",
    name: "Блок - TPN-020 mini-red",
    price: 8200,
    favorite: false,
    sales: 0.25,
    url: "../../assets/productsCards/powers/TPN-020 mini, red.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722028",
    name: "Блок - Tuffking PS-100",
    price: 6500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/powers/Tuffking PS-100.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "powers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772229",
    name: "Бумага - Dr.Tattoo Care Freehand Sheet Carbon",
    price: 2000,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/printers/Dr.Tattoo Care Freehand Sheet Carbon.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "printers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772230",
    name: "Принтер - DragonHawk Print",
    price: 19200,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/printers/DragonHawk.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "printers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772231",
    name: "Очиститель - Killin Color Transfer CREAM",
    price: 1700,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/printers/killin Color Transfer CREAM.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "printers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772232",
    name: "Лазер для удаления татту - Lasertech 1800i",
    price: 235000,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/printers/Lasertech 1800i.jpg",
    absent: false,
    hit: false,
    novelty: true,
    promotion: false,
    category: "printers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772233",
    name: "Бумага - S8 RED TATTOO STENCIL PAPER (USA)",
    price: 1500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/printers/S8 RED TATTOO STENCIL PAPER (USA).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "printers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772234",
    name: "Очиститель - Skillin Color Cartridge cleaner",
    price: 1800,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/printers/Skillin Color Cartridge cleaner.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "printers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772235",
    name: "Принтер - SKILLIN COLOR mg2545s",
    price: 48520,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/printers/SKILLIN COLOR mg2545s на СНПЧ.jpg",
    absent: false,
    hit: true,
    novelty: false,
    promotion: false,
    category: "printers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772236",
    name: "Бумага - Skillin Color Transfer Paper",
    price: 2200,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/printers/Skillin Color Transfer Paper,.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "printers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772237",
    name: "Принтер - SKILLIN COLOR ts3340 wifi",
    price: 42000,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/printers/SKILLIN COLOR ts3340 wifi.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "printers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772238",
    name: "Картридж - Skillin Color",
    price: 6800,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/printers/Skillin Color.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "printers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772239",
    name: "Бумага - Spirit Classic Thermal Legal A4",
    price: 2500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/printers/Spirit Classic Thermal Legal A4 (USA).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "printers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772240",
    name: "Бумага - Spirit Classic Thermal Roll (USA)",
    price: 2300,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/printers/Spirit Classic Thermal Roll (USA).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "printers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772241",
    name: "Принтер - Tattoo Stencil Printer MT200.jpg",
    price: 35600,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/printers/Tattoo Stencil Printer MT200.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "printers",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772242",
    name: "Наконечник - Blackbird -7DT (5 ШТ.)",
    price: 500,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/blackbird -7DT (5 ШТ.).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772243",
    name: "Наконечник - Blackbird- 3R (5 ШТ.)",
    price: 450,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/blackbird- 3R (5 ШТ.).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772244",
    name: "Наконечник - Blackbird-3DT (5 ШТ.)",
    price: 620,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/blackbird-3DT (5 ШТ.).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772245",
    name: "Наконечник - Blackbird-9R (50 ШТ.)",
    price: 5700,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/blackbird-9R (50 ШТ.).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed4556567722446",
    name: "Наконечник - Blackdbird- 9DT (50 ШТ.)",
    price: 4850,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/blackdbird- 9DT (50 ШТ.).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772247",
    name: "Наконечник - Flat 5F",
    price: 80,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/Flat 5F.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772248",
    name: "Наконечник - Flat 15F",
    price: 90,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/Flat 15F.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772249",
    name: "Наконечник - Nextfly-3DT (5 ШТ.)",
    price: 700,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/nextfly-3DT (5 ШТ.).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772250",
    name: "Наконечник - Nextfly-7DT (5 ШТ.)",
    price: 650,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/nextfly-7DT (5 ШТ.).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772251",
    name: "Наконечник - Nextfly-13DT (50 ШТ.)",
    price: 6800,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/nextfly-13DT (50 ШТ.).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772252",
    name: "Наконечник - Round 13R",
    price: 120,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/Round 13R.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772253",
    name: "Наконечник - ROUND BLUE 9R (50 ШТ.)",
    price: 7820,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/ROUND BLUE 9R (50 ШТ.).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772254",
    name: "Наконечник - ROUND BLUE 13R (50 ШТ.)",
    price: 6530,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/ROUND BLUE 13R (50 ШТ.).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772255",
    name: "Наконечник - ROUND BLUE 18R (5 ШТ.)",
    price: 780,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/ROUND BLUE 18R (5 ШТ.).jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772256",
    name: "Наконечник - Stainless Steel 10 Tips kit",
    price: 3250,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/Stainless Steel 10 Tips kit.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772257",
    name: "Наконечник - Stainless Steel 22 Tips kit",
    price: 5910,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/Stainless Steel 22 Tips kit.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772258",
    name: "Наконечник - Stainless Steel Diamond 5D",
    price: 220,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/Stainless Steel Diamond 5D.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772259",
    name: "Наконечник - Stainless Steel Flat 5F",
    price: 250,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/Stainless Steel Flat 5F.jpg",
    absent: false,
    hit: 0.1,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772260",
    name: "Наконечник - Stainless Steel Flat 15F",
    price: 320,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/Stainless Steel Flat 15F.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772261",
    name: "Наконечник - Stainless Steel Round 7R",
    price: 260,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/Stainless Steel Round 7R.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772262",
    name: "Наконечник - Stainless Steel Round 13R",
    price: 310,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/Stainless Steel Round 13R.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772263",
    name: "Наконечник - Verge Diamond 11D",
    price: 2420,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/Verge Diamond 11D.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772264",
    name: "Наконечник - Verge Flat 9F",
    price: 2000,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/Verge Flat 9F.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  },
  {
    _id: "67rdca3eeb7f6fgeed455656772265",
    name: "Наконечник - Verge Round 15",
    price: 1950,
    favorite: false,
    sales: false,
    url: "../../assets/productsCards/tips/Verge Round 15.jpg",
    absent: false,
    hit: false,
    novelty: false,
    promotion: false,
    category: "tips",
    popular: false
  }

];

if (!localStorage.getItem("products")) {
  localStorage.setItem("products", JSON.stringify(products));
}

const fetchAll = () =>
  new Promise((resolve) => {
    window.setTimeout(function () {
      resolve(JSON.parse(localStorage.getItem("products")));
    }, 2000);
  });

const getById = (id) =>
  new Promise((resolve) => {
    window.setTimeout(function () {
      resolve(
        JSON.parse(localStorage.getItem("products")).find(
          (product) => product._id === id
        )
      );
    }, 1000);
  });
export default {
  fetchAll,
  getById
};
